language: node_js
script:
- yarn lint
- yarn test && yarn codecov
- yarn build
deploy:
  provider: npm
  email: contact@carlossless.io
  api_key:
    secure: HAdDkHQOsa18KvUyd1AAu5HNYlvRA+xTpdB9lw+t6TZfKx19EOHgRDSMZ1agEDVeR2I/2ijg7KMTuPQpPSG7UsXkxVYQ/Jd4XgtHJCe9Wv9DW15Jwn96e5QE6wAedR8YD91xjwPSwRfE/4n+BOrPW0WGb6MjSapvrA7MZV9DfpK0Hv5A/Mn5y8CKOptnlXXW5+6NaS7BDEs/J8G/jXpbopJb2W+U5hbnPxTlGn8dP2PaL3vZBfP/poBmqWml4THaz5/Nhm33xMbtJthYYDZbekBaeuGz2StmRpC23r4/YDoTTuGaJ03EkuzBrojUmc9+czynGtZmQb4S6Mfklj/wlpnL1ngsj9RI3+p2hwgcaii+ACRmQuhEecPQzFlvVYkPQ2YF+6IqCrYYOFo2fUustUehAzzhap/UkgvegVw8NPClPbjWfU155OC6zqkOMeqELxKF1Ey5lc8C46Bj91PjVn5AwrLl9lSsrhy4t8owVyBnVhlsb9bU+iKGQklBQOee1o8X6iF0AQ8Tir7jTc7QJt0TCLdMSw1hjdaSW/HfpEMB4ZFnkfjIzUbOp1w9kc2BZVRSznjQi/eCdTECYplVD4yEMDZVQLh3thIeIgpAcU1/rkl65DerAPCABXpx1VRo+GoiKPZMCP7i0JkLttq0A1GnzHfZYxNBOf88jn/AOyY=
  on:
    tags: true
    repo: carlossless/lokalise
