language: node_js
script:
- yarn lint
- yarn test && yarn codecov
- yarn build
deploy:
  provider: npm
  email: contact@carlossless.io
  skip_cleanup: true
  api_key:
    secure: ZxitFnQlpUwpGVzbU+nub47boPvuK5dJ7zGcd6rWELoRe0pMrtlNvK0vI+WvodtwkQWuz+fdRAFLFKS/XPp1yU3gz5P27j5jjVu6XNZ2/hOXnfngR7A2QHxCeQs/B90qy17LB7Toks914Ln53/p5nzBMvyYPFGsI/4O5Dgi5rzGIe9jjQokAOj+Pp2qNiAH4nhORcyCUOn2bQPfgzj1aAm2xH/7jjuINhtTjnRDIq+e0qT/LRBH0l5kMQlRTp9rbe2tEAx2yIovVAFBzvSZV2Q6qBzyaG2X6ApCYuQoAgAhABC+bBt6quiUps2gibtGOYQONXhMI9E40cfzqwP4WD78V7EyM75V5RPwl6CqJk2Aijmj6Vwj7d/4A/4XyYIP8EBpvpEiEXr317dwUzLsmkDsIYiMKG8nRiCmixSNBuAAPXCan0aL4eXKgU1QVQw+L3f5nBjP2FyUhA2rJDm1jEh2XRJn0N6rrG/8qsQxNF8wfqw8nu1ZUDoI97FuJyMGGJU3FmvQyXuUHJ1gDfJO5HPVg6SC09uhNe+0POAtjMub2E5y3D78JxcsAZQ3+8Zm/QPmlA96g6YunMWGvFZ3s3mMTbYM8jBbRoZUCzFO1yvr4SA2bJurBEJNtsJaNHy0buT4+T3HYM/EMWkdihD1G+K5njABhaBuxK/4BTGeAJ/c=
  on:
    tags: true
    repo: carlossless/lokalise
